name: CI
on: 
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '@generate'
          reaction: rocket
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Install modules and run it
        run: yarn
        if: steps.check.outputs.triggered == 'true'
      - name: Generate Curriculum
        run: yarn generate:curriculum:ci
        env: 
          GHUB: 'try again'
        if: steps.check.outputs.triggered == 'true'

